server:
  port: 8001

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: eurekaServer